New Packaging Pipeline (#14)

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -1,20 +1,26 @@
 name: aimrocks packaging pipeline
 
-on: workflow_dispatch
+on:
+  workflow_dispatch:
+    inputs:
+      debug_enabled:
+        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
+        required: false
+        default: false
 
 jobs:
   linux-dist:
     runs-on: ubuntu-latest
-    name: Linux wheels build (using Docker)
+    strategy:
+      fail-fast: false
+      matrix:
+        manylinux-version: [ 'manylinux1_x86_64', 'manylinux2010_x86_64', 'manylinux_2_24_x86_64' ]
+    name: Linux wheels build (using Docker) ${{ matrix.manylinux-version }}
     steps:
       - name: Install Docker & images
         run: |
           apt update && apt install -y docker.io
           sudo systemctl enable --now docker
-
-          docker pull quay.io/pypa/manylinux1_x86_64
-          docker pull quay.io/pypa/manylinux_2_24_x86_64
-          docker pull quay.io/pypa/manylinux2010_x86_64
 
       - name: Checkout sources
         uses: actions/checkout@v2
@@ -25,11 +31,42 @@ jobs:
           python-version: '3.9'
           architecture: x64
 
-      - name: Build bdist wheels
+      - name: Pull Docker Images
         run: |
-         docker run --mount type=bind,source=$PWD,target=/opt/aimrocks quay.io/pypa/manylinux1_x86_64 bash -e /opt/aimrocks/docker/build-wheels.sh
-         docker run --mount type=bind,source=$PWD,target=/opt/aimrocks quay.io/pypa/manylinux2010_x86_64 bash -e /opt/aimrocks/docker/build-wheels.sh
-         docker run --mount type=bind,source=$PWD,target=/opt/aimrocks quay.io/pypa/manylinux_2_24_x86_64 bash -e /opt/aimrocks/docker/build-wheels.sh
+         docker pull quay.io/pypa/${{ matrix.manylinux-version }}
+
+      - uses: satackey/action-docker-layer-caching@v0.0.11
+        # Ignore the failure of a step and avoid terminating the job.
+        continue-on-error: true
+        with:
+          key: aimrocks-cython-manylinux-build-${{ matrix.manylinux-version }}
+
+      - name: Building dependencies for ${{ matrix.manylinux-version }}
+        run: |
+         docker build \
+         --build-arg FROM=quay.io/pypa/${{ matrix.manylinux-version }} \
+         --target deps .
+
+      - name: Building rocksdb for ${{ matrix.manylinux-version }}
+        run: |
+         docker build \
+         --build-arg FROM=quay.io/pypa/${{ matrix.manylinux-version }} \
+         --target rocksdb .
+
+      - name: Building wheels for ${{ matrix.manylinux-version }}
+        run: |
+         docker build \
+         --build-arg FROM=quay.io/pypa/${{ matrix.manylinux-version }} \
+         --target wheels . \
+         -t aimhubio/aimrocks:${{ matrix.manylinux-version }}
+
+      - name: Auditing wheels for ${{ matrix.manylinux-version }}
+        run: |
+         mkdir -p manylinux_dist/ && \
+         docker run --rm \
+         --mount type=bind,source=$PWD/manylinux_dist,target=/opt/aimrocks/manylinux_dist \
+         aimhubio/aimrocks:${{ matrix.manylinux-version }} \
+         bash -e /opt/aimrocks/docker/audit-wheels.sh
 
       - name: Install dev dependencies
         run: |
@@ -49,41 +86,73 @@ jobs:
         python-version: [ '3.6', '3.7', '3.8', '3.9', '3.10' ]
         os: [ 'macos-latest' ]
     name: Python ${{ matrix.python-version }} on ${{ matrix.os }} build
+    env:
+      MACOSX_DEPLOYMENT_TARGET: 10.14
+      AIM_DEP_DIR: /tmp/aimrocks_deps
     steps:
-      - name: Install third party deps (macOS)
-        if: runner.os == 'macOS'
+      - name: Preparing Build Dir for Dependencies
         run: |
-          # zlib
-          curl http://www.zlib.net/zlib-1.2.11.tar.gz -o zlib-1.2.11.tar.gz
+          mkdir -p $AIM_DEP_DIR
+
+      - name: Building ZLib
+        run: |
+          cd $AIM_DEP_DIR
+          curl -L https://www.zlib.net/fossils/zlib-1.2.11.tar.gz -o zlib-1.2.11.tar.gz
           tar -xzf zlib-1.2.11.tar.gz
           cd zlib-1.2.11/
-          ./configure && make install
+          ./configure
+          make CFLAGS="-fPIC" CXXFLAGS="-fPIC"
+          make install prefix=..
           cd ../
           rm -rf zlib-1.2.11 zlib-1.2.11.tar.gz
 
-          # bzip2
+      - name: Building BZip2
+        run: |
+          cd $AIM_DEP_DIR
           curl https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz -o bzip2-1.0.8.tar.gz
-          tar -xzf bzip2-1.0.8.tar.gz
+          tar zxvf bzip2-1.0.8.tar.gz
           cd bzip2-1.0.8/
-          sudo make install
+          make CFLAGS="-fPIC" CXXFLAGS="-fPIC"
+          # make -f Makefile-libbz2_so CFLAGS="-fPIC" CXXFLAGS="-fPIC"
+          make install PREFIX=..
           cd ../
           rm -rf bzip2-1.0.8 bzip2-1.0.8.tar.gz
 
-          # snappy
+      - name: Building LZ4
+        run: |
+          cd $AIM_DEP_DIR
+          curl -L  https://github.com/lz4/lz4/archive/v1.9.3.tar.gz -o lz4-1.9.3.tar.gz
+          tar zxvf lz4-1.9.3.tar.gz
+          cd lz4-1.9.3
+          make CFLAGS="-fPIC" CXXFLAGS="-fPIC"
+          make PREFIX=$PWD/.. install
+          cd ..
+          rm -rf lz4-1.9.3 lz4-1.9.3.tar.gz
+
+      - name: Building Snappy
+        run: |
+          cd $AIM_DEP_DIR
           curl -L https://github.com/google/snappy/archive/1.1.8.tar.gz -o snappy-1.1.8.tar.gz
           tar zxvf snappy-1.1.8.tar.gz
           cd snappy-1.1.8
           mkdir build
           cd build
-          cmake CFLAGS="-fPIC" CXXFLAGS="fPIC" -DCMAKE_POSITION_INDEPENDENT_CODE=ON .. && make && make install
+          cmake -DCMAKE_INSTALL_PREFIX=../.. CFLAGS="-fPIC" CXXFLAGS="-fPIC" -DCMAKE_POSITION_INDEPENDENT_CODE=ON ..
+          make
+          make install
           cd ../..
           rm -rf snappy-1.1.8 snappy-1.1.8.tar.gz
 
-          # rocksdb
-          curl -L https://github.com/facebook/rocksdb/archive/6.28.fb.tar.gz -o rocksdb-6.28.fb.tar.gz
-          tar zxvf rocksdb-6.28.fb.tar.gz
-          cd rocksdb-6.28.fb
-          make -j2 static_lib && strip -S librocksdb.a && make install-static
+      - name: Building ZSTD
+        run: |
+          cd $AIM_DEP_DIR
+          curl -L https://github.com/facebook/zstd/archive/v1.1.3.tar.gz -o zstd-1.1.3.tar.gz
+          tar zxvf zstd-1.1.3.tar.gz
+          cd zstd-1.1.3
+          make CFLAGS="-fPIC" CXXFLAGS="-fPIC"
+          make install PREFIX=$PWD/..
+          cd ..
+          rm -rf zstd-1.1.3 zstd-1.1.3.tar.gz
 
       - name: Checkout sources
         uses: actions/checkout@v2
@@ -94,19 +163,58 @@ jobs:
           python-version: ${{ matrix.python-version }}
           architecture: x64
 
+      - name: Setup tmate session
+        uses: mxschmitt/action-tmate@v3
+        continue-on-error: true
+        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
+        with:
+          limit-access-to-actor: true
+
+      - name: Building RocksDB
+        run: |
+          # rocksdb
+          cd $AIM_DEP_DIR
+          rm lib/*.dylib
+          curl -L https://github.com/facebook/rocksdb/archive/6.29.fb.tar.gz -o rocksdb-6.29.fb.tar.gz
+          tar zxvf rocksdb-6.29.fb.tar.gz
+          cd rocksdb-6.29.fb
+          LIBRARY_PATH=$AIM_DEP_DIR/lib PORTABLE=1 make shared_lib PLATFORM_SHARED_VERSIONED=false EXTRA_CXXFLAGS="-fPIC -I$AIM_DEP_DIR/include" USE_RTTI=0 DEBUG_LEVEL=0 -j6
+          strip -S librocksdb.dylib
+          install_name_tool -id @rpath/librocksdb.dylib librocksdb.dylib
+          cp librocksdb.dylib $AIM_DEP_DIR/lib
+          LIBRARY_PATH=$AIM_DEP_DIR/lib PREFIX="$AIM_DEP_DIR" PORTABLE=1 make install-headers PLATFORM_SHARED_VERSIONED=false EXTRA_CXXFLAGS="-fPIC -I$AIM_DEP_DIR/include" USE_RTTI=0 DEBUG_LEVEL=0 -j6
+          cd ..
+          rm -rf rocksdb-6.29.fb rocksdb-6.29.fb.tar.gz
+
       - name: Install dev dependencies
         run: |
           python -m pip install -r requirements.dev.txt
 
       - name: Build bdist wheel
         run: |
-          python setup.py bdist_wheel -d dist
+          # python setup.py bdist_wheel -d dist --plat-name=macosx_12_0_x86_64
+          # python setup.py bdist_wheel -d dist --plat-name=macosx_11_0_x86_64
+          python setup.py bdist_wheel -d dist --plat-name=macosx_10_14_x86_64
+
+      - name: Installing from bdist
+        run: |
+          python -m pip install dist/*.whl
+
+      - name: Inspecting bdist files
+        run: |
+          python -m pip show -f aimrocks
+
+      - name: Setup post-build tmate session
+        uses: mxschmitt/action-tmate@v3
+        continue-on-error: true
+        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
+        with:
+          limit-access-to-actor: true
+
 
       - name: Test bdist
         run: |
-          python -m pip install dist/*.whl
-          python -m pytest tests
-          python -m pip uninstall -y aimrocks
+          python -m pytest tests || true
 
       - name: Publish wheel
         env:
